/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewtonInterface.java
 *
 * Created on 15/11/2011, 10:43:04 AM
 */
package Interpolacion;

import Vistas.Interpolation;
import Vistas.Mensage;
import Vistas.OneVariableList;

/**
 *
 * @author Juan Rivillas
 */
public class NewtonInterface extends javax.swing.JFrame {


    private double [][] matriz;
    private String polinomio;
    private int n;
    private double valorPolinomio = 0;   
    private Interpolation interpolation;
    
    private OneVariableList oneVariableList;
    
    
    /** Creates new form NewtonInterface */
    public NewtonInterface(Interpolation interpolation2) {
        initComponents();
        interpolation = interpolation2;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(40, 150, 450, 90);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(310, 260, 90, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(40, 260, 260, 96);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(440, 300, 50, 20);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N");
        jLabel2.setBounds(400, 290, 40, 40);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("Help");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(290, 370, 53, 23);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Resize");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(400, 260, 90, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEWTON DIVIDED ");
        jLabel1.setBounds(50, 0, 500, 80);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIFFERENCES");
        jLabel3.setBounds(90, 70, 360, 80);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("EXIT");
        jButton4.setBounds(40, 370, 55, 23);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Return To Methdo's List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(120, 370, 150, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fond1.jpg"))); // NOI18N
        jLabel4.setBounds(0, 0, 540, 400);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    int n = Integer.parseInt(jTextField1.getText());
    double[] xi = new double[n];
    double[] fx = new double[n];
    
    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);
        
        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    calcularMatriz(xi,fx);   
}//GEN-LAST:event_jButton1ActionPerformed



private void calcularMatriz(double [] xi, double[]fx) {        
        n = Integer.parseInt(jTextField1.getText());
        matriz = new double[n][n + 1];
        for(int i = 0; i < n ; i++){
            matriz[i][0] = xi[i];
            matriz[i][1] = fx[i];
        }

        int loop = 0;
        for(int i = 2; i < n + 1; i++){
            int min = 0;
            int max = 1 + loop;
            for(int j = i - 1; j < n; j++){
                matriz[j][i] = ( matriz[j][i - 1] - matriz[j - 1][i - 1] )
                        / ( matriz[min][0] - matriz[max][0]);
                min ++;
                max ++;
            }
            loop++;
        }
        System.out.println("voy a imprimir");
        for (int i = 0; i < matriz.length; i++) {
            
            for (int j = 0; j < matriz[0].length; j++) {
                jTable1.setValueAt(matriz[i][j], i, j);
                System.out.println(matriz[i][j]);
            }
            System.out.println("-------------");
        } 
        
        CalcularPolinomio(valorPolinomio);
    }


    public double CalcularPolinomio(double x){
        double resultado = 0;
        polinomio ="P(x) = ";
        for (int i = 0 ; i < n ; i++) {            
            double multi = 1;
            polinomio += matriz[i][i+1]+"";
            for (int j = 0 ; j < i; j++) {
                multi = multi * (x - matriz[j][0]);
                polinomio += " ( x" +" - "+ matriz[j][0]+" )";
            }
            resultado = resultado + matriz[i][i+1] * multi;
            if(i + 1 != n){                
                polinomio += " + ";
            }
        }
        jTextArea1.setText(polinomio);
        return resultado;
    }

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    try {
        int n = Integer.parseInt(jTextField1.getText());
       
        Object[][] b = new Object[n][2 + (n-1)];
        String [] nombres=new String[n+1];
        nombres[0]="x";
        nombres[1]="f(x)";
        jTable1.setModel(new javax.swing.table.DefaultTableModel(b, nombres));
        
    } catch (Exception ex) {
        System.out.println("exception en em metodo de redimension " + ex);
    }
    
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
            String titulo="Newton Differences ";
    String texto="You have to enter the vector of x values and the vector of FX values.  The Newton method with \n"
+"divided differences returns a polynomial. One of the advantages of this method is that it can be  \n"
+"calculated easily with a recursive procedure and in its algorithm the calculation of the coefficients \n"
+"of the interpolation polynomial just requires the differences Fx1, fx12 fx1..n  \n";

    Mensage a=new Mensage(titulo,texto);
       a.setVisible(true);
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    interpolation.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton5ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
