package Diferenciacion;

import Vistas.MethodList;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewtonInterface.java
 *
 * Created on 15/11/2011, 10:43:04 AM
 */

import Vistas.Mensage;

/**
 *
 * @author Juan Rivillas
 */
public class Differentiation extends javax.swing.JFrame {

    private double[][] matriz;
    private String polinomio;
    private int n;
    private double valorPolinomio = 0;
    private MethodList methodList;

    /** Creates new form NewtonInterface */
    public Differentiation(MethodList methodList2) {
        methodList = methodList2;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "f(x)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(20, 110, 580, 90);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(190, 410, 53, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(20, 300, 590, 96);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.setBounds(540, 210, 60, 20);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36));
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("N");
        jLabel2.setBounds(496, 200, 40, 40);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Resize");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(390, 230, 90, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("2 backward");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(20, 210, 90, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("2 forward");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(120, 210, 80, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("3 backward");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(20, 240, 87, 23);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("3 central");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(210, 240, 75, 23);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText("3 forward");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(120, 240, 79, 23);
        jLayeredPane1.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setText("5 backward");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(20, 270, 87, 23);
        jLayeredPane1.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setText("5 central");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(210, 270, 75, 23);
        jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton10.setText("5 forward");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.setBounds(120, 270, 80, 23);
        jLayeredPane1.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36));
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("H");
        jLabel3.setBounds(500, 240, 30, 30);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField2.setBounds(540, 240, 60, 20);
        jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton11.setText("Return Method's Menu");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.setBounds(20, 410, 160, 23);
        jLayeredPane1.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton12.setText("EXIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jButton12.setBounds(530, 410, 55, 23);
        jLayeredPane1.add(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48));
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("DIFFERENTIATION");
        jLabel1.setBounds(40, 10, 540, 80);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo11.jpg"))); // NOI18N
        jLabel4.setBounds(10, 0, 610, 440);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    try {
        int n = Integer.parseInt(jTextField1.getText());

        Object[][] b = new Object[n][2];
        jTable1.setModel(new javax.swing.table.DefaultTableModel(b, new String[]{"x", "Fx"}));

    } catch (Exception ex) {
        System.out.println("exception en em metodo de redimension " + ex);
    }

}//GEN-LAST:event_jButton3ActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
     String titulo="Differentiation Method ";
    String texto="The numerical differentiation is an approximation to a real derived of a function. We can use \n"
         +"this with 2, 3 or 5 points. The more points we use, the more exactly our approximation would \n"
         +"be. Also, It is said that these approximations are very unstable because the little values of h \n"
         +"needed to make smaller the truncation error makes the rounding error bigger. \n";

    Mensage a=new Mensage(titulo,texto);
       a.setVisible(true);  
    
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    int n = Integer.parseInt(jTextField1.getText());
   double h = Double.parseDouble(jTextField2.getText().toString());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    back2Points(current,h, xi, fx);// TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText().toString());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    forward2Points(current,h, xi, fx);// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    back3Points(current,h, xi, fx);// TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    mid3Points(current,h, xi, fx);// TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
   double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    forward3Points(current,h, xi, fx);// TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    back5Points(current,h, xi, fx);
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    mid5Points(current,h, xi, fx);
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// TODO add your handling code here:
    int n = Integer.parseInt(jTextField1.getText());
    double h = Double.parseDouble(jTextField2.getText());
    int current=jTable1.getSelectedRow();
    double[] xi = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < xi.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        xi[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + xi[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        String a = jTable1.getValueAt(i, 1).toString();
        fx[i] = Double.parseDouble(a);

        System.out.println("y" + i + "=" + fx[i]);
    }
    System.out.println("llame calcular");
    forward5Points(current,h, xi, fx);
}//GEN-LAST:event_jButton10ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    
    methodList.setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton11ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

    System.exit(0);
}//GEN-LAST:event_jButton12ActionPerformed
    
public void back2Points(int i,double h,double [] x,double [] fx){
         
        double h2=x[i]-x[i-1];
        //System.out.println("h2=" + h2);
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (fx[i]-fx[i-brinco])/h;
        String ecuaciones = ("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void forward2Points(int i,double h,double [] x,double [] fx){
        double h2=x[i+1]-x[i];
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (fx[i+brinco]-fx[i])/h;
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void back3Points(int i,double h,double [] x,double [] fx){
        double h2=x[i]-x[i-1];
        //System.out.println("h2=" + h2);
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        //System.out.println("f[i-h]=" +fx[i-brinco]);
       // System.out.println("f[i-2h]=" +fx[i-2*brinco]);
        double resultado= (-3*fx[i]+4*fx[i-brinco]-fx[i-2*brinco])/(-2*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void forward3Points(int i,double h,double [] x,double [] fx){
        double h2=x[i+1]-x[i];
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (-3*fx[i]+4*fx[i+brinco]-fx[i+2*brinco])/(2*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void mid3Points(int i,double h,double [] x,double [] fx){
        double h2=x[i+1]-x[i];
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (fx[i+brinco]-fx[i-brinco])/(2*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void back5Points(int i,double h,double [] x,double [] fx){
        double h2=x[i]-x[i-1];
        //System.out.println("h2=" + h2);
        int brinco= (int) Math.round(h/h2);
       double resultado= (-25*fx[i]+48*fx[i-brinco]-36*fx[i-2*brinco]+16*fx[i-3*brinco]-3*fx[i-4*brinco])/(-12*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void forward5Points(int i,double h,double [] x,double [] fx){
        double h2=x[i+1]-x[i];
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (-25*fx[i]+48*fx[i+brinco]-36*fx[i+2*brinco]+16*fx[i+3*brinco]-3*fx[i+4*brinco])/(12*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    public void mid5Points(int i,double h,double [] x,double [] fx){
        double h2=x[i+1]-x[i];
        int brinco= (int) Math.round(h/h2);
        //System.out.println("brinco= " + brinco);
        double resultado= (fx[i-2*brinco]-8*fx[i-brinco]+8*fx[i+brinco]-fx[i+2*brinco])/(12*h);
        String ecuaciones =("f'(x)= " + resultado);
        jTextArea1.setText(ecuaciones);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
