/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultipleRoots.java
 *
 * Created on 16/11/2011, 08:00:07 PM
 */
package Metodos1;

import Vistas.MethodList;
import Vistas.OneVariableList;

/**
 *
 * @author Mao Ricardo
 */
public class MultipleRoots extends javax.swing.JFrame {
    
    private FunctionList listFunc;
    private OneVariableList oneVariableList;
    
    private double x0;
    private int iter;
    private double tolerance;
    
    private boolean errorRela = true;
    private boolean errorAbs = true;
    
    /** Creates new form MultipleRoots */
    public MultipleRoots(FunctionList c, OneVariableList oneVariableList2) {
        initComponents();
        oneVariableList = oneVariableList2;
        listFunc = c;
    }
    
    public  void raizMultiple(double x0, double tolerancia, int iter, boolean errorRela, boolean errorAbs){
        
                 
        double fx0= listFunc.f(x0);        
        double fpx0= listFunc.fp(x0);        
        double f2px0= listFunc.f2p(x0);        
        
        int row = 0;
        Object[][] matriz = new Object[iter + 1][6];
        matriz[row][0] = 0;
        matriz[row][1] = x0;
        matriz[row][2] = fx0;
        matriz[row][3] = fpx0;
        matriz[row][4] = f2px0;
        matriz[row][5] = "na";
        
        double error=tolerancia+1;
        double denom=Math.pow(fpx0, 2)- fx0 * f2px0;
        int counter=1;
        while(error>tolerancia && fx0!=0 && counter<iter && denom!=0){
            double x1=x0 - fx0 * fpx0 / denom;
            error=Math.abs(x0-x1);
            if(errorAbs == true){
                    error = Math.abs(x1 - x0);
            }
            if(errorRela == true){
                   error = Math.abs((x1 - x0)/x1);
            } 
            fx0=listFunc.f(x1);            
            fpx0=listFunc.fp(x1);
            f2px0=listFunc.f2p(x1);
            denom=Math.pow(fpx0, 2)- fx0 * f2px0;
            matriz[counter][0] = counter;
            matriz[counter][1] = x1;
            matriz[counter][2] = fx0;
            matriz[counter][3] = fpx0;
            matriz[counter][4] = f2px0;
            matriz[counter][5] = error;
            x0=x1;
            counter++;
        }
        if(fx0==0){
            System.out.println("La raiz es=" + x0);
        }else if(error <= tolerancia){
            jTextArea1.setText(x0+ " es una aproximacion a una raiz con tolerancia " + tolerancia);            
        }else if(denom==0){
            jTextArea1.setText("Error: division por 0");
        }else{
            jTextArea1.setText("El metodo fallo en " + iter + " iteraciones.");
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"Iteración", "xi", "f(xi)", "f´(xi)","f´´(xi)","Error"}));    
     }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(60, 110, 460, 90);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input X0");
        jLabel1.setBounds(40, 300, 80, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the tolerance");
        jLabel2.setBounds(40, 240, 140, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Iterations");
        jLabel3.setBounds(40, 270, 110, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(190, 230, 60, 20);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField2.setBounds(190, 260, 60, 20);
        jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField3.setBounds(190, 300, 60, 20);
        jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToggleButton1.setText("Calculate");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToggleButton1.setBounds(267, 320, 90, 23);
        jLayeredPane1.add(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(280, 210, 240, 96);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Return To Method´s Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(360, 320, 170, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Absolute Error");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.setBounds(170, 350, 110, 23);
        jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Relative Error");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jCheckBox2.setBounds(41, 350, 120, 23);
        jLayeredPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("EXIT");
        jButton2.setBounds(360, 350, 55, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MULTIPLE ROOTS");
        jLabel4.setBounds(40, 20, 500, 80);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo11.jpg"))); // NOI18N
        jLabel5.setBounds(0, 0, 550, 420);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
// TODO add your handling code here:
    x0 = Double.parseDouble(jTextField1.getText());    
    iter = Integer.parseInt(jTextField2.getText());    
    tolerance = Double.parseDouble(jTextField3.getText());
    
    
    if(jCheckBox1.isSelected() == true){
            errorRela = true;
    }             
    if(jCheckBox2.isSelected() == true){
            errorAbs = true;
    }
    
    raizMultiple(x0,tolerance,iter, errorRela, errorAbs);
}//GEN-LAST:event_jToggleButton1ActionPerformed

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
// TODO add your handling code here:
    jCheckBox2.setSelected(!jCheckBox1.isSelected());
}//GEN-LAST:event_jCheckBox1ActionPerformed

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
// TODO add your handling code here:
    jCheckBox1.setSelected(!jCheckBox2.isSelected());
}//GEN-LAST:event_jCheckBox2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    oneVariableList.setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
