/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Simpson38.java
 *
 * Created on 14/11/2011, 05:12:52 PM
 */
package Integracion;

import Vistas.MethodList;
import Vistas.Mensage;

/**
 *
 * @author Juan Rivillas
 */
public class SimpsonMethods extends javax.swing.JFrame {

    private MethodList methodList;
       
    
    /** Creates new form Simpson38 */
    public SimpsonMethods(MethodList methodList2) {
        methodList = methodList2;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "x", "f(x)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        jScrollPane1.setBounds(20, 120, 490, 140);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(250, 330, 260, 96);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Result");
        jLabel2.setBounds(450, 300, 60, 25);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Simpson 1/3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(20, 270, 110, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Simpson 3/8");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(20, 300, 110, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Trapecio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(20, 330, 110, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Generalizado");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.setBounds(140, 270, 110, 23);
        jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Help");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(183, 330, 60, 23);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(440, 270, 70, 20);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("N");
        jLabel3.setBounds(390, 260, 40, 30);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Resize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(303, 270, 80, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("Return Method's List");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(250, 440, 150, 23);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setText("EXIT");
        jButton7.setBounds(440, 440, 73, 23);
        jLayeredPane1.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INTEGRARTION");
        jLabel1.setBounds(50, 20, 430, 90);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo13.jpg"))); // NOI18N
        jLabel4.setBounds(0, 0, 520, 470);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    double integral = 0;
    int n = Integer.parseInt(jTextField1.getText());
    
    double[] x = new double[n];
    double[] y = new double[n];
    double sumPares = 0.0;
    double sumImpares = 0.0;   
    double h = 0.0;
        
    for (int i = 0; i < x.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        x[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + x[i]);
    }

    for (int i = 0; i < y.length; i++) {
        y[i] = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        System.out.println("y" + i + "=" + y[i]);
    }
       
    if (jCheckBox1.isSelected()){

        for(int i = 1; i < x.length-1; i++){
            if (x.length % 2 == 1) {                
                if (x[i] % 2 == 1){                    
                    sumImpares += y[i];                    
                }else{                    
                    sumPares += y[i];                    
                }
            }    
        }
        h = (x[x.length-1] - x[0]) / (x.length-1);
        System.out.println("El h :"+h);
        integral =  (h / 3) *(y[0]+y[y.length-1]+ 2*sumPares + 4*sumImpares);  
        
        jTextArea1.setText("integral = " + integral);
           
    }else{
        
        if (x.length % 2 == 1) {
            h = (x[x.length-1] - x[0]) / 2;
            int mid = x.length / 2;
            integral = (h / 3) * (y[0] + 4 * y[mid] + y[y.length-1]);
            jTextArea1.setText("integral = " + integral);
            
        } else {
             jTextArea1.setText("Error,  debe ser impar");
        }  

    }
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    double integral = 0;
    int n = Integer.parseInt(jTextField1.getText());
    double[] x = new double[n];
    double[] y = new double[n];
    
    for (int i = 0; i < x.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        x[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + x[i]);
    }

    for (int i = 0; i < y.length; i++) {
        y[i] = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        System.out.println("y" + i + "=" + y[i]);
    }

    if (jCheckBox1.isSelected()) {

        if (x.length % 2 != 0) {
            double h = (x[x.length - 1] - x[0]) / 3;
            int mid1 = (x.length / 3) * 1;
            int mid2 = (x.length / 3) * 2;
            double sumImpares = sumaImpares(y);
            double sumPares = sumaPares(y);

            integral = (h / 3) * (y[0] + (4 * sumImpares) + (2 * sumPares) + y[y.length - 1]);
            jTextArea1.setText("Integral = " + integral);

        } else {
            jTextArea1.setText("Numero par en los datos");
        }
    }else{
        
        if (x.length % 2 != 0) {

            double h = (x[x.length - 1] - x[0]) / 3;
            int mid1 = (x.length / 3) * 1;
            int mid2 = (x.length / 3) * 2;

            integral = 3 * (h / 8) * (y[0] + 3 * y[mid1] + 3 * y[mid2] + y[y.length - 1]);
            jTextArea1.setText("Integral = " + integral);
            
        } else {
            jTextArea1.setText("Numero par en los datos");
        }
    
    
    }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    try {
        int n = Integer.parseInt(jTextField1.getText());
       
        Object[][] b = new Object[n][2];
        jTable1.setModel(new javax.swing.table.DefaultTableModel(b, new String[]{"x" , "Fx"}));
        
    } catch (Exception ex) {
        System.out.println("exception en em metodo de redimension " + ex);
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    double integral = 0;
    int n = Integer.parseInt(jTextField1.getText());
    double[] x = new double[n];
    double[] fx = new double[n];

    for (int i = 0; i < x.length; i++) {
        String a = jTable1.getValueAt(i, 0).toString();
        x[i] = Double.parseDouble(a);
        System.out.println("x" + i + "=" + x[i]);
    }

    for (int i = 0; i < fx.length; i++) {
        fx[i] = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
        System.out.println("fx" + i + "=" + fx[i]);
    }

    try {

//        Object[][] b = new Object[n][2];
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(b, new String[]{"x", "fx"}));

    } catch (Exception ex) {
        System.out.println("exception en em metodo de redimension " + ex);
    }


    if (jCheckBox1.isSelected()) {

        double h = (x[x.length - 1] - x[0]) / x.length;
        System.out.println("h = " + h);
        double sumaInterna = sumaInterna(fx);
        integral = (h / 2) * (fx[0] + fx[fx.length - 1] + 2 * sumaInterna / 2);
        jTextArea1.setText("Integral = " + integral);

    } else {

        double h = x[x.length - 1] - x[0];
        integral = h * ((fx[fx.length - 1] + fx[0]) / 2);
        jTextArea1.setText("Integral = " + integral);
    }

}//GEN-LAST:event_jButton3ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    methodList.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    String titulo="Simpson Methods ";
    String texto="You have to enter the vector of x values and the vector of FX values.  The Newton method with \n"
+"divided differences returns a polynomial. One of the advantages of this method is that it can be  \n"
+"calculated easily with a recursive procedure and in its algorithm the calculation of the coefficients \n"
+"of the interpolation polynomial just requires the differences Fx1, fx12 fx1..n  \n";

    Mensage a=new Mensage(titulo,texto);
       a.setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

    public double sumaImpares(double[] y) {
        double sumaImpares = 0;
        for (int i = 1; i < y.length - 1; i = i + 2) {
            sumaImpares = sumaImpares + y[i];
        }

        return sumaImpares;
    }

    public double sumaPares(double[] y) {
        double sumaPares = 0;
        for (int i = 2; i < y.length - 2; i = i + 2) {
            sumaPares += y[i];
        }

        return sumaPares;
    }
    
     private double sumaInterna(double [] fx) {
        
        double suma = 0;
        
        for (int i = 1; i < fx.length - 1; i++) {
            suma = suma + fx[i];
        }        
        System.out.println("suma interna" + suma);
        return suma;
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
